rbac:
  create: true
defaultBackend:
  enabled: false
controller:
  ingressClass: "nginx"
  service:
    externalTrafficPolicy: "Local"
  extraArgs:
    default-ssl-certificate: "cloudbees-core/core-tls"
tcp:
  50000: "cloudbees-core/cjoc:50000"